import { spawnSync } from 'child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';
import { tmpdir } from 'os';
import { afterEach, beforeEach, describe, expect, it } from '@jest/globals';

const CONFIG_KEYS_TO_CLEAR = [
  'SEMANTIC_SCHOLAR_API_KEY',
  'PAPER_SEARCH_UNPAYWALL_EMAIL',
  'UNPAYWALL_EMAIL',
  'CORE_API_KEY',
  'EASYSCHOLAR_KEY',
  'CROSSREF_MAILTO'
];

describe('setup command', () => {
  let tempDir: string;
  let configFile: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'paper-search-setup-test-'));
    configFile = join(tempDir, 'config.json');
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  it('auto-generates a random common email for missing Unpaywall and Crossref email prompts', () => {
    const result = runSetup('\n\n\n\n\n');

    expect(result.status).toBe(0);
    expect(result.stderr).toContain('auto-generates a random Gmail-format address');

    const output = JSON.parse(result.stdout);
    expect(output.updated).toEqual(['PAPER_SEARCH_UNPAYWALL_EMAIL', 'CROSSREF_MAILTO']);
    expect(output.autoGenerated).toEqual(['PAPER_SEARCH_UNPAYWALL_EMAIL', 'CROSSREF_MAILTO']);
    expect(output.skipped).toEqual(['SEMANTIC_SCHOLAR_API_KEY', 'CORE_API_KEY', 'EASYSCHOLAR_KEY']);

    const config = readConfig();
    expect(config.PAPER_SEARCH_UNPAYWALL_EMAIL).toMatch(/^paper\.search\.[a-f0-9]{12}@gmail\.com$/);
    expect(config.CROSSREF_MAILTO).toBe(config.PAPER_SEARCH_UNPAYWALL_EMAIL);
  });

  it('keeps existing email values when setup input is blank', () => {
    writeFileSync(
      configFile,
      JSON.stringify(
        {
          PAPER_SEARCH_UNPAYWALL_EMAIL: 'real-user@example.org',
          CROSSREF_MAILTO: 'contact@example.org'
        },
        null,
        2
      )
    );

    const result = runSetup('\n\n\n\n\n');

    expect(result.status).toBe(0);
    const output = JSON.parse(result.stdout);
    expect(output.kept).toEqual(['PAPER_SEARCH_UNPAYWALL_EMAIL', 'CROSSREF_MAILTO']);
    expect(output.autoGenerated).toEqual([]);

    const config = readConfig();
    expect(config.PAPER_SEARCH_UNPAYWALL_EMAIL).toBe('real-user@example.org');
    expect(config.CROSSREF_MAILTO).toBe('contact@example.org');
  });

  it('installs the bundled skill when an explicit setup target is provided', () => {
    const result = runSetup('\n\n\n\n\n', ['--install-skills', 'agents', '--skills-root', tempDir]);

    expect(result.status).toBe(0);
    const output = JSON.parse(result.stdout);
    expect(output.skills.skipped).toBe(false);
    expect(output.skills.destinations).toEqual([
      expect.objectContaining({
        target: 'agents',
        path: join(tempDir, '.agents', 'skills', 'paper-search')
      })
    ]);
    expect(output.skills.result.installedCount).toBe(1);
    expect(existsSync(join(tempDir, '.agents', 'skills', 'paper-search', 'SKILL.md'))).toBe(true);
    expect(output.capabilityProfile.entries.find((entry: any) => entry.id === 'journal_metrics').requiredKeys).toEqual([
      'EASYSCHOLAR_KEY'
    ]);
  });

  it('does not keep config setup as a duplicate setup entrypoint', () => {
    const result = runCli(['config', 'setup', '--skip-skills'], '\n\n\n\n\n');

    expect(result.status).toBe(1);
    expect(result.stderr).toContain('Unknown config command: setup');
    expect(result.stdout).toContain('"code":"UNKNOWN_CONFIG_COMMAND"');
  });

  function runSetup(input: string, extraArgs: string[] = ['--skip-skills']) {
    return runCli(['setup', ...extraArgs], input);
  }

  function runCli(args: string[], input = '') {
    const env: NodeJS.ProcessEnv = {
      ...process.env,
      PAPER_SEARCH_CONFIG_FILE: configFile
    };
    for (const key of CONFIG_KEYS_TO_CLEAR) {
      delete env[key];
    }

    return spawnSync(process.execPath, [join(process.cwd(), 'node_modules/.bin/tsx'), 'src/cli.ts', ...args], {
      cwd: process.cwd(),
      env,
      input,
      encoding: 'utf8'
    });
  }

  function readConfig(): Record<string, string> {
    expect(existsSync(configFile)).toBe(true);
    return JSON.parse(readFileSync(configFile, 'utf8')) as Record<string, string>;
  }
});
